apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infra
  - ../../../apps/aria2/overlays/prod
  - ../../../apps/ledger/overlays/dev
  - ../../../apps/n8n/overlays/prod
  - ../../../apps/it-tools/overlays/prod
  - ../../../apps/plex/overlays/prod
  - ../../../apps/postgres/overlays/ledger-dev
  - ../../../apps/postgres/overlays/keycloak
  - ../../../apps/pgadmin/overlays/prod
  - ../../../apps/homarr/overlays/prod
  - ../../../apps/metabase/overlays/prod
  - ../../../apps/postgres/overlays/metabase
  - ../../../apps/excalidraw/overlays/prod
  - ../../../apps/sonarr/overlays/prod


patchesStrategicMerge:
  - patch-ingress-nginx-service.yaml
