apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
      annotations:
        homelab.dev/rollout-nonce: "2025-11-04-01"
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox:1.36
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          command:
            - sh
            - -c
            - |
              mkdir -p /downloads/tv /downloads/movies /downloads/anime \
                && chown -R 1000:1000 /downloads/tv /downloads/movies /downloads/anime
          volumeMounts:
            - name: downloads-tv
              mountPath: /downloads/tv
            - name: downloads-movies
              mountPath: /downloads/movies
            - name: downloads-anime
              mountPath: /downloads/anime
      containers:
        - name: radarr
          image: linuxserver/radarr:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7878
          env:
            - name: PUID
              valueFrom:
                configMapKeyRef:
                  name: radarr-config
                  key: PUID
            - name: PGID
              valueFrom:
                configMapKeyRef:
                  name: radarr-config
                  key: PGID
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: radarr-config
                  key: TZ
          volumeMounts:
            - name: config
              mountPath: /config
            - name: plex-media
              mountPath: /media
            - name: plex-media
              mountPath: /downloads
            - name: downloads-tv
              mountPath: /downloads/tv
            - name: downloads-movies
              mountPath: /downloads/movies
            - name: downloads-anime
              mountPath: /downloads/anime
      volumes:
        - name: plex-media
          hostPath:
            path: /mnt/gdrive/Videos
            type: Directory
        - name: downloads-tv
          hostPath:
            path: /mnt/gdrive/Videos/TV
            type: DirectoryOrCreate
        - name: downloads-movies
          hostPath:
            path: /mnt/gdrive/Videos/Movies
            type: DirectoryOrCreate
        - name: downloads-anime
          hostPath:
            path: /mnt/gdrive/Videos/Anime
            type: DirectoryOrCreate
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config
