apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n
resources:
  - ../../base
  - namespace.yaml
  - networkpolicy-egress-vpn.yaml
patchesStrategicMerge:
  - patch-proxy.yaml
