apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metabase
spec:
  ingressClassName: nginx
  rules:
    - host: metabase.jamaguchi.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: metabase
                port:
                  name: http

