apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - manifests/namespace.yaml
  - manifests/deployment.yaml
configMapGenerator:
  - name: cloudflared-config
    namespace: networking
    files:
      - config.yaml=./config/config.yaml
generatorOptions:
  disableNameSuffixHash: false
