apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
      annotations:
        homelab.dev/rollout-nonce: "2025-11-04-01"
    spec:
      containers:
        - name: sonarr
          image: linuxserver/sonarr:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8989
          env:
            - name: PUID
              valueFrom:
                configMapKeyRef:
                  name: sonarr-config
                  key: PUID
            - name: PGID
              valueFrom:
                configMapKeyRef:
                  name: sonarr-config
                  key: PGID
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: sonarr-config
                  key: TZ
          volumeMounts:
            - name: config
              mountPath: /config
            - name: plex-media
              mountPath: /media
            - name: plex-media
              mountPath: /downloads
            - name: downloads-tv
              mountPath: /downloads/tv
            - name: downloads-movies
              mountPath: /downloads/movies
            - name: downloads-anime
              mountPath: /downloads/anime
      volumes:
        - name: plex-media
          hostPath:
            path: /mnt/gdrive/Videos
            type: Directory
        - name: downloads-tv
          hostPath:
            path: /mnt/gdrive/Videos/TV
            type: DirectoryOrCreate
        - name: downloads-movies
          hostPath:
            path: /mnt/gdrive/Videos/Movies
            type: DirectoryOrCreate
        - name: downloads-anime
          hostPath:
            path: /mnt/gdrive/Videos/Anime
            type: DirectoryOrCreate
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config
