apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
      annotations:
        homelab.dev/rollout-nonce: "2025-11-16-02"
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox:1.36
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          command:
            - sh
            - -c
            - |
              mkdir -p /downloads/tv /downloads/movies /downloads/anime \
                && chown -R 1000:1000 /downloads/tv /downloads/movies /downloads/anime
          volumeMounts:
            - name: downloads
              mountPath: /downloads
      containers:
        - name: sonarr
          image: linuxserver/sonarr:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8989
          env:
            - name: PUID
              valueFrom:
                configMapKeyRef:
                  name: sonarr-config
                  key: PUID
            - name: PGID
              valueFrom:
                configMapKeyRef:
                  name: sonarr-config
                  key: PGID
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: sonarr-config
                  key: TZ
          volumeMounts:
            - name: config
              mountPath: /config
            - name: library-tv
              mountPath: /media/tv
            - name: library-movies
              mountPath: /media/movies
            - name: library-anime
              mountPath: /media/anime
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: library-tv
          hostPath:
            path: /mnt/gdrive/Videos/TV
            type: Directory
        - name: library-movies
          hostPath:
            path: /mnt/gdrive/Videos/Movies
            type: Directory
        - name: library-anime
          hostPath:
            path: /mnt/gdrive/Videos/Anime
            type: Directory
        - name: downloads
          hostPath:
            path: /downloads
            type: Directory
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config
